(() => {
 const API=(window.X10_ADMIN_CONFIG&&window.X10_ADMIN_CONFIG.API_BASE)||'/api'; let token=sessionStorage.getItem('x10_admin_token')||''; let filter='all';
 const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
 const message=(sel,text,error=false)=>{const el=$(sel);el.innerHTML=text?`<div class="admin-message${error?' error':''}">${esc(text)}</div>`:''};
 async function api(path,opt={}){const headers={Accept:'application/json',...(opt.headers||{})}; if(token)headers.Authorization='Bearer '+token; const r=await fetch(API+path,{...opt,headers});let d={};try{d=await r.json()}catch{}if(!r.ok){const validation=Object.values(d.errors||{}).flat()[0];const fallback=r.status===413?'The selected file is larger than the server upload limit.':`Request failed (${r.status})`;throw Object.assign(new Error(validation||d.message||fallback),{status:r.status})}return d}
 async function boot(){try{const meta=await api('/admin/meta');if(!meta.admin_exists){showSetup();return}if(!token){showLogin();return}await loadDashboard()}catch(e){showLogin();message('#auth-message',e.message,true)}}
 function showLogin(){ $('#auth-view').hidden=false;$('#dashboard-view').hidden=true;$('#login-form').hidden=false;$('#setup-form').hidden=true;$('#auth-title').textContent='Admin sign in';$('#auth-copy').textContent='Manage software releases and access approvals.' }
 function showSetup(){ $('#auth-view').hidden=false;$('#dashboard-view').hidden=true;$('#login-form').hidden=true;$('#setup-form').hidden=false;$('#auth-title').textContent='Create the first admin';$('#auth-copy').textContent='Use the one-time setup key from the Laravel backend .env file.' }
 async function loadDashboard(){try{const d=await api('/admin/dashboard');$('#auth-view').hidden=true;$('#dashboard-view').hidden=false;$('#admin-email').textContent=d.admin.email;renderStats(d.stats);await Promise.all([loadRequests(),loadReleases()])}catch(e){if(e.status===401){token='';sessionStorage.removeItem('x10_admin_token');showLogin()}else throw e}}
 function renderStats(s){$('#stats').innerHTML=`<article><span>Pending</span><strong>${s.pending}</strong><small>Needs a decision</small></article><article><span>Approved</span><strong>${s.approved}</strong><small>Active / historical approvals</small></article><article><span>Rejected</span><strong>${s.rejected}</strong><small>Not granted</small></article><article><span>Downloads</span><strong>${s.downloads}</strong><small>Protected deliveries</small></article>`}
 async function loadRequests(){const d=await api('/admin/requests?status='+encodeURIComponent(filter));const box=$('#requests');if(!d.data.length){box.innerHTML='<div class="admin-empty">No requests in this view.</div>';return}box.innerHTML=d.data.map(r=>`<article class="request-card"><div class="request-summary"><div class="avatar">${esc((r.name||'?')[0].toUpperCase())}</div><div class="request-person"><div><strong>${esc(r.name)}</strong><span class="status ${esc(r.status)}">${esc(r.status)}</span></div><a href="mailto:${esc(r.email)}">${esc(r.email)}</a><small>${esc(r.passion)} · ${esc(r.request_code)} · ${esc(r.created_at)}</small></div><div class="request-build"><span>${/android/i.test(r.release.platform)?'APK':'EXE'}</span><div><strong>${esc(r.release.title)}</strong><small>v${esc(r.release.version)} · ${esc(r.release.platform)}</small></div></div></div><div class="purpose-box"><span>INTENDED USE</span><p>${esc(r.purpose)}</p></div>${r.admin_note?`<div class="admin-note"><span>ADMIN NOTE</span>${esc(r.admin_note)}</div>`:''}<div class="request-actions">${r.status==='pending'?`<input class="admin-inline-note" id="note-${r.id}" maxlength="300" placeholder="Optional admin note"><button class="admin-btn primary" data-approve="${r.id}">Approve access</button><button class="admin-btn danger" data-reject="${r.id}">Reject</button>`:r.status==='approved'?`<div class="approved-tools"><span>Expires ${esc(r.expires_at||'—')} · ${r.download_count||0} download(s) · User unlocks from the public status checker</span></div>`:`<span class="decision-label">Rejected ${esc(r.reviewed_at||'')}</span>`}</div></article>`).join('');box.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>decide(b.dataset.approve,'approve'));box.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>decide(b.dataset.reject,'reject'))}
 async function decide(id,action){try{const note=$('#note-'+id)?.value||'';await api(`/admin/requests/${id}/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({admin_note:note})});await loadDashboard()}catch(e){message('#dash-message',e.message,true)}}
 async function loadReleases(){const d=await api('/admin/releases');const box=$('#releases');if(!d.data.length){box.innerHTML='<div class="admin-empty">No builds uploaded yet.</div>';return}box.innerHTML=d.data.map(x=>`<article class="app-row"><span class="app-file-icon">${/android/i.test(x.platform)?'APK':/msi/i.test(x.platform)?'MSI':/zip/i.test(x.platform)?'ZIP':'EXE'}</span><div class="app-main"><strong>${esc(x.title)}</strong><span>${esc(x.platform)} · v${esc(x.version)} · ${esc(x.size_human)}</span><small>${esc(x.original_name)}</small></div><span class="status ${x.is_active?'approved':'rejected'}">${x.is_active?'active':'hidden'}</span><div class="app-actions"><button class="admin-btn" data-toggle="${x.id}" data-active="${x.is_active?1:0}">${x.is_active?'Hide':'Activate'}</button><button class="admin-btn danger" data-delete="${x.id}">Delete</button></div></article>`).join('');box.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=async()=>{try{await api(`/admin/releases/${b.dataset.toggle}/toggle`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({is_active:b.dataset.active!=='1'})});await loadDashboard()}catch(e){message('#dash-message',e.message,true)}});box.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this release and all related access requests?'))return;try{await api(`/admin/releases/${b.dataset.delete}`,{method:'DELETE'});await loadDashboard()}catch(e){message('#dash-message',e.message,true)}})}
 $('#login-form').addEventListener('submit',async e=>{e.preventDefault();message('#auth-message','');try{const d=await api('/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget).entries()))});token=d.token;sessionStorage.setItem('x10_admin_token',token);await loadDashboard()}catch(err){message('#auth-message',err.message,true)}});
 $('#setup-form').addEventListener('submit',async e=>{e.preventDefault();try{const d=await api('/admin/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget).entries()))});token=d.token;sessionStorage.setItem('x10_admin_token',token);await loadDashboard()}catch(err){message('#auth-message',err.message,true)}});
 $('#logout-btn').onclick=async()=>{try{await api('/admin/logout',{method:'POST'})}catch{}token='';sessionStorage.removeItem('x10_admin_token');showLogin()};
 $('#filters').addEventListener('click',e=>{const b=e.target.closest('[data-status]');if(!b)return;filter=b.dataset.status;$('#filters').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));loadRequests()});
 const modal=$('#upload-modal');function open(){modal.classList.add('open');modal.setAttribute('aria-hidden','false')}function close(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}$('#open-upload').onclick=open;$('#open-upload-2').onclick=open;modal.querySelectorAll('[data-close]').forEach(x=>x.onclick=close);
 $('#upload-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;const button=form.querySelector('button[type="submit"]');const file=form.elements.build.files[0];message('#upload-message','');if(!file)return message('#upload-message','Choose an APK, EXE, MSI, or ZIP file.',true);if(file.size>200*1024*1024)return message('#upload-message','Maximum allowed build size is 200 MB.',true);const oldText=button.textContent;button.disabled=true;button.textContent=`Uploading ${(file.size/1024/1024).toFixed(1)} MB…`;try{await api('/admin/releases',{method:'POST',body:new FormData(form)});form.reset();close();message('#dash-message','Release uploaded and published.');await loadDashboard()}catch(err){message('#upload-message',err.message,true)}finally{button.disabled=false;button.textContent=oldText}});
 $('#password-form').addEventListener('submit',async e=>{e.preventDefault();try{await api('/admin/change-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget).entries()))});e.currentTarget.reset();message('#dash-message','Password updated.')}catch(err){message('#dash-message',err.message,true)}});
 boot();
})();
